In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\admin\Desktop\Data Science\Course-2021\03-Pandas\mpg.csv')

In [3]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [4]:
# Categorical column - model year column
df['model_year'].value_counts()

73    40
78    36
76    34
82    31
75    30
70    29
79    29
80    29
81    29
71    28
72    28
77    28
74    27
Name: model_year, dtype: int64

In [5]:
# sort by index
df['model_year'].value_counts().sort_index()

70    29
71    28
72    28
73    40
74    27
75    30
76    34
77    28
78    36
79    29
80    29
81    29
82    31
Name: model_year, dtype: int64

In [6]:
# sort by values
df['model_year'].value_counts().sort_values()

74    27
71    28
72    28
77    28
70    29
79    29
80    29
81    29
75    30
82    31
76    34
78    36
73    40
Name: model_year, dtype: int64

In [7]:
# sum the number of value
df['model_year'].value_counts().sum()

398

In [8]:
# Answer the question how much the 'mpg' change per year?
# Using the groupby() - the groupby() is the lazy function
# The groupby() don't do anything until the aggregate function call out
df.groupby('model_year').mean()['mpg']

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [9]:
# Calling out multiple index
df.groupby(['model_year', 'cylinders']).mean()

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [10]:
# Calling out the column names
df.groupby(['model_year', 'cylinders']).mean().columns

Index(['mpg', 'displacement', 'weight', 'acceleration', 'origin'], dtype='object')

In [11]:
# calling out the Multi Index
df.groupby(['model_year', 'cylinders']).mean().index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [12]:
# Calling out the column you want
df.groupby(['model_year', 'cylinders']).mean()['mpg']

model_year  cylinders
70          4            25.285714
            6            20.500000
            8            14.111111
71          4            27.461538
            6            18.000000
            8            13.428571
72          3            19.000000
            4            23.428571
            8            13.615385
73          3            18.000000
            4            22.727273
            6            19.000000
            8            13.200000
74          4            27.800000
            6            17.857143
            8            14.200000
75          4            25.250000
            6            17.583333
            8            15.666667
76          4            26.766667
            6            20.000000
            8            14.666667
77          3            21.500000
            4            29.107143
            6            19.500000
            8            16.000000
78          4            29.576471
            5            20.300000
            6            19.066667
            8            19.050000
79          4            31.525000
            5            25.400000
            6            22.950000
            8            18.630000
80          3            23.700000
            4            34.612000
            5            36.400000
            6            25.900000
81          4            32.814286
            6            23.428571
            8            26.600000
82          4            32.071429
            6            28.333333
Name: mpg, dtype: float64

In [13]:
# Describe the table
df.groupby(['model_year', 'cylinders']).describe()

                       mpg                                                    \
                     count       mean       std   min     25%    50%     75%
model_year cylinders
70         4           7.0  25.285714  1.112697  24.0  24.500  25.00  26.000
           6           4.0  20.500000  1.732051  18.0  20.250  21.00  21.250
           8          18.0  14.111111  2.609685   9.0  14.000  14.50  15.000
71         4          13.0  27.461538  3.502746  22.0  25.000  27.00  30.000
           6           8.0  18.000000  1.069045  16.0  17.750  18.00  19.000
           8           7.0  13.428571  0.786796  12.0  13.000  14.00  14.000
72         3           1.0  19.000000       NaN  19.0  19.000  19.00  19.000
           4          14.0  23.428571  3.056249  18.0  21.250  23.00  25.750
           8          13.0  13.615385  1.502135  11.0  13.000  13.00  14.000
73         3           1.0  18.000000       NaN  18.0  18.000  18.00  18.000
           4          11.0  22.727273  3.319365  19.0  20.000  22.00  25.000
           6           8.0  19.000000  2.203893  16.0  18.000  18.00  20.250
           8          20.0  13.200000  1.361114  11.0  12.000  13.00  14.000
74         4          15.0  27.800000  2.932576  24.0  26.000  26.00  31.000
           6           7.0  17.857143  2.267787  15.0  16.000  18.00  19.500
           8           5.0  14.200000  1.095445  13.0  14.000  14.00  14.000
75         4          12.0  25.250000  3.333712  22.0  23.000  24.00  26.000
           6          12.0  17.583333  2.020726  15.0  15.750  18.00  19.000
           8           6.0  15.666667  2.422120  13.0  14.250  15.50  16.000
76         4          15.0  26.766667  3.825976  19.0  25.000  27.00  29.000
           6          10.0  20.000000  2.494438  16.5  18.125  19.50  22.000
           8           9.0  14.666667  1.767767  13.0  13.000  14.50  16.000
77         3           1.0  21.500000       NaN  21.5  21.500  21.50  21.500
           4          14.0  29.107143  4.039129  21.5  25.625  30.00  31.250
           6           5.0  19.500000  1.767767  17.5  18.500  19.00  20.500
           8           8.0  16.000000  0.845154  15.0  15.500  15.75  16.250
78         4          17.0  29.576471  6.384799  21.1  23.900  29.50  32.800
           5           1.0  20.300000       NaN  20.3  20.300  20.30  20.300
           6          12.0  19.066667  1.548802  16.2  18.000  19.30  20.500
           8           6.0  19.050000  1.048332  17.5  18.375  19.30  19.775
79         4          12.0  31.525000  4.349739  22.3  28.150  32.70  34.275
           5           1.0  25.400000       NaN  25.4  25.400  25.40  25.400
           6           6.0  22.950000  3.851104  19.8  20.300  21.05  25.475
           8          10.0  18.630000  2.757636  15.5  16.925  17.90  19.025
80         3           1.0  23.700000       NaN  23.7  23.700  23.70  23.700
           4          25.0  34.612000  6.597621  23.6  29.800  33.80  40.800
           5           1.0  36.400000       NaN  36.4  36.400  36.40  36.400
           6           2.0  25.900000  9.616652  19.1  22.500  25.90  29.300
81         4          21.0  32.814286  3.844904  25.8  30.000  33.00  34.700
           6           7.0  23.428571  4.139531  17.6  21.300  23.50  24.800
           8           1.0  26.600000       NaN  26.6  26.600  26.60  26.600
82         4          28.0  32.071429  5.054727  23.0  27.750  32.00  36.000
           6           3.0  28.333333  8.504901  22.0  23.500  25.00  31.500

                           displacement              ... acceleration        \
                       max        count        mean  ...          75%   max
model_year cylinders                                 ...
70         4          27.0          7.0  107.000000  ...       17.500  20.5
           6          22.0          4.0  199.000000  ...       15.625  16.0
           8          18.0         18.0  367.555556  ...       12.000  18.5
71         4          35.0         13.0  101.846154  ...       19.000  20.5
           6          19.0          8.0  243.375000  ...       15.500  15.5
           8          14.0          7.0  371.714286  ...       12.500  13.5
72         3          19.0          1.0   70.000000  ...       13.500  13.5
           4          28.0         14.0  111.535714  ...       18.000  23.5
           8          17.0         13.0  344.846154  ...       13.500  16.0
73         3          18.0          1.0   70.000000  ...       13.500  13.5
           4          29.0         11.0  109.272727  ...       19.250  21.0
           6          23.0          8.0  212.250000  ...       16.500  18.0
           8          16.0         20.0  365.250000  ...       13.000  14.5
74         4          32.0         15.0   96.533333  ...       16.750  21.0
           6          21.0          7.0  230.428571  ...       17.000  18.0
           8          16.0          5.0  315.200000  ...       15.500  16.0
75         4          33.0         12.0  114.833333  ...       17.000  18.5
           6          21.0         12.0  233.750000  ...       19.125  21.0
           8          20.0          6.0  330.500000  ...       13.875  14.5
76         4          33.0         15.0  106.333333  ...       17.550  22.2
           6          24.0         10.0  221.400000  ...       17.675  21.0
           8          17.5          9.0  324.000000  ...       13.900  15.0
77         3          21.5          1.0   80.000000  ...       13.500  13.5
           4          36.0         14.0  106.500000  ...       16.950  18.6
           6          22.0          5.0  220.400000  ...       17.700  19.0
           8          17.5          8.0  335.750000  ...       14.600  19.0
78         4          43.1         17.0  112.117647  ...       16.700  21.5
           5          20.3          1.0  131.000000  ...       15.900  15.9
           6          20.8         12.0  213.250000  ...       17.450  19.2
           8          20.2          6.0  300.833333  ...       13.575  15.5
79         4          37.3         12.0  113.583333  ...       16.325  24.8
           5          25.4          1.0  183.000000  ...       20.100  20.1
           6          28.8          6.0  205.666667  ...       17.800  18.2
           8          23.9         10.0  321.400000  ...       15.350  22.2
80         3          23.7          1.0   70.000000  ...       12.500  12.5
           4          46.6         25.0  111.000000  ...       18.100  23.7
           5          36.4          1.0  121.000000  ...       19.900  19.9
           6          32.7          2.0  196.500000  ...       16.875  18.7
81         4          39.1         21.0  108.857143  ...       17.300  20.7
           6          30.7          7.0  184.000000  ...       16.850  19.6
           8          26.6          1.0  350.000000  ...       19.000  19.0
82         4          44.0         28.0  118.571429  ...       18.050  24.6
           6          38.0          3.0  225.000000  ...       16.700  17.0

                     origin
                      count      mean       std  min  25%  50%   75%  max
model_year cylinders
70         4            7.0  2.285714  0.487950  2.0  2.0  2.0  2.50  3.0
           6            4.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
           8           18.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
71         4           13.0  1.923077  0.862316  1.0  1.0  2.0  3.00  3.0
           6            8.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
           8            7.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
72         3            1.0  3.000000       NaN  3.0  3.0  3.0  3.00  3.0
           4           14.0  1.928571  0.828742  1.0  1.0  2.0  2.75  3.0
           8           13.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
73         3            1.0  3.000000       NaN  3.0  3.0  3.0  3.00  3.0
           4           11.0  2.000000  0.632456  1.0  2.0  2.0  2.00  3.0
           6            8.0  1.250000  0.707107  1.0  1.0  1.0  1.00  3.0
           8           20.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
74         4           15.0  2.200000  0.774597  1.0  2.0  2.0  3.00  3.0
           6            7.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
           8            5.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
75         4           12.0  2.166667  0.717741  1.0  2.0  2.0  3.00  3.0
           6           12.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
           8            6.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
76         4           15.0  1.866667  0.743223  1.0  1.0  2.0  2.00  3.0
           6           10.0  1.300000  0.674949  1.0  1.0  1.0  1.00  3.0
           8            9.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
77         3            1.0  3.000000       NaN  3.0  3.0  3.0  3.00  3.0
           4           14.0  1.857143  0.864438  1.0  1.0  2.0  2.75  3.0
           6            5.0  1.400000  0.894427  1.0  1.0  1.0  1.00  3.0
           8            8.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
78         4           17.0  2.117647  0.927520  1.0  1.0  2.0  3.00  3.0
           5            1.0  2.000000       NaN  2.0  2.0  2.0  2.00  2.0
           6           12.0  1.166667  0.389249  1.0  1.0  1.0  1.00  2.0
           8            6.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
79         4           12.0  1.583333  0.792961  1.0  1.0  1.0  2.00  3.0
           5            1.0  2.000000       NaN  2.0  2.0  2.0  2.00  2.0
           6            6.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
           8           10.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
80         3            1.0  3.000000       NaN  3.0  3.0  3.0  3.00  3.0
           4           25.0  2.200000  0.816497  1.0  2.0  2.0  3.00  3.0
           5            1.0  2.000000       NaN  2.0  2.0  2.0  2.00  2.0
           6            2.0  2.000000  1.414214  1.0  1.5  2.0  2.50  3.0
81         4           21.0  2.095238  0.943650  1.0  1.0  2.0  3.00  3.0
           6            7.0  1.714286  0.951190  1.0  1.0  1.0  2.50  3.0
           8            1.0  1.000000       NaN  1.0  1.0  1.0  1.00  1.0
82         4           28.0  1.714286  0.937180  1.0  1.0  1.0  3.00  3.0
           6            3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0

[43 rows x 40 columns]

In [14]:
# Transpose
df.groupby(['model_year', 'cylinders']).describe().transpose()

model_year                   70                                     71  \
cylinders                     4            6            8            4
mpg          count     7.000000     4.000000    18.000000    13.000000
             mean     25.285714    20.500000    14.111111    27.461538
             std       1.112697     1.732051     2.609685     3.502746
             min      24.000000    18.000000     9.000000    22.000000
             25%      24.500000    20.250000    14.000000    25.000000
             50%      25.000000    21.000000    14.500000    27.000000
             75%      26.000000    21.250000    15.000000    30.000000
             max      27.000000    22.000000    18.000000    35.000000
displacement count     7.000000     4.000000    18.000000    13.000000
             mean    107.000000   199.000000   367.555556   101.846154
             std       8.660254     0.816497    59.076443    23.053728
             min      97.000000   198.000000   302.000000    71.000000
             25%     100.500000   198.750000   309.750000    88.000000
             50%     107.000000   199.000000   355.000000    97.000000
             75%     111.500000   199.250000   421.750000   116.000000
             max     121.000000   200.000000   455.000000   140.000000
weight       count     7.000000     4.000000    18.000000    13.000000
             mean   2292.571429  2710.500000  3940.055556  2056.384615
             std     263.055037   112.837641   496.964488   217.933300
             min    1835.000000  2587.000000  3086.000000  1613.000000
             25%    2182.000000  2632.750000  3518.750000  1955.000000
             50%    2372.000000  2711.000000  3805.500000  2074.000000
             75%    2402.500000  2788.750000  4370.500000  2220.000000
             max    2672.000000  2833.000000  4732.000000  2408.000000
acceleration count     7.000000     4.000000    18.000000    13.000000
             mean     16.000000    15.500000    11.194444    16.961538
             std       2.661453     0.408248     2.668657     2.536907
             min      12.500000    15.000000     8.000000    14.000000
             25%      14.500000    15.375000     9.625000    14.500000
             50%      15.000000    15.500000    10.250000    18.000000
             75%      17.500000    15.625000    12.000000    19.000000
             max      20.500000    16.000000    18.500000    20.500000
origin       count     7.000000     4.000000    18.000000    13.000000
             mean      2.285714     1.000000     1.000000     1.923077
             std       0.487950     0.000000     0.000000     0.862316
             min       2.000000     1.000000     1.000000     1.000000
             25%       2.000000     1.000000     1.000000     1.000000
             50%       2.000000     1.000000     1.000000     2.000000
             75%       2.500000     1.000000     1.000000     3.000000
             max       3.000000     1.000000     1.000000     3.000000

model_year                                        72               \
cylinders                     6            8       3            4
mpg          count     8.000000     7.000000     1.0    14.000000
             mean     18.000000    13.428571    19.0    23.428571
             std       1.069045     0.786796     NaN     3.056249
             min      16.000000    12.000000    19.0    18.000000
             25%      17.750000    13.000000    19.0    21.250000
             50%      18.000000    14.000000    19.0    23.000000
             75%      19.000000    14.000000    19.0    25.750000
             max      19.000000    14.000000    19.0    28.000000
displacement count     8.000000     7.000000     1.0    14.000000
             mean    243.375000   371.714286    70.0   111.535714
             std      11.867573    32.438220     NaN    14.167221
             min     225.000000   318.000000    70.0    96.000000
             25%     232.000000   350.500000    70.0    97.125000
             50%     250.000000   383.000000    70.0   116.500000
             75%     250.000000   400.000000    70.0   121.000000
             max     258.000000   400.000000    70.0   140.000000
weight       count     8.000000     7.000000     1.0    14.000000
             mean   3171.875000  4537.714286  2330.0  2382.642857
             std     259.952434   415.550524     NaN   274.992477
             min    2634.000000  4096.000000  2330.0  2100.000000
             25%    3094.750000  4181.500000  2330.0  2198.250000
             50%    3285.000000  4464.000000  2330.0  2283.000000
             75%    3308.750000  4850.500000  2330.0  2481.500000
             max    3439.000000  5140.000000  2330.0  2979.000000
acceleration count     8.000000     7.000000     1.0    14.000000
             mean     14.750000    12.214286    13.5    17.214286
             std       1.000000     0.755929     NaN     2.423557
             min      13.000000    11.500000    13.5    14.500000
             25%      14.250000    11.750000    13.5    15.625000
             50%      15.250000    12.000000    13.5    16.750000
             75%      15.500000    12.500000    13.5    18.000000
             max      15.500000    13.500000    13.5    23.500000
origin       count     8.000000     7.000000     1.0    14.000000
             mean      1.000000     1.000000     3.0     1.928571
             std       0.000000     0.000000     NaN     0.828742
             min       1.000000     1.000000     3.0     1.000000
             25%       1.000000     1.000000     3.0     1.000000
             50%       1.000000     1.000000     3.0     2.000000
             75%       1.000000     1.000000     3.0     2.750000
             max       1.000000     1.000000     3.0     3.000000

model_year                           73  ...           79      80  \
cylinders                     8       3  ...            8       3
mpg          count    13.000000     1.0  ...    10.000000     1.0
             mean     13.615385    18.0  ...    18.630000    23.7
             std       1.502135     NaN  ...     2.757636     NaN
             min      11.000000    18.0  ...    15.500000    23.7
             25%      13.000000    18.0  ...    16.925000    23.7
             50%      13.000000    18.0  ...    17.900000    23.7
             75%      14.000000    18.0  ...    19.025000    23.7
             max      17.000000    18.0  ...    23.900000    23.7
displacement count    13.000000     1.0  ...    10.000000     1.0
             mean    344.846154    70.0  ...   321.400000    70.0
             std      42.160104     NaN  ...    36.914917     NaN
             min     302.000000    70.0  ...   260.000000    70.0
             25%     307.000000    70.0  ...   302.750000    70.0
             50%     350.000000    70.0  ...   334.000000    70.0
             75%     351.000000    70.0  ...   350.750000    70.0
             max     429.000000    70.0  ...   360.000000    70.0
weight       count    13.000000     1.0  ...    10.000000     1.0
             mean   4228.384615  2124.0  ...  3862.900000  2420.0
             std     264.578765     NaN  ...   254.455170     NaN
             min    3672.000000  2124.0  ...  3420.000000  2420.0
             25%    4098.000000  2124.0  ...  3751.250000  2420.0
             50%    4274.000000  2124.0  ...  3870.000000  2420.0
             75%    4422.000000  2124.0  ...  3951.250000  2420.0
             max    4633.000000  2124.0  ...  4360.000000  2420.0
acceleration count    13.000000     1.0  ...    10.000000     1.0
             mean     13.000000    13.5  ...    15.400000    12.5
             std       1.307032     NaN  ...     2.718251     NaN
             min      11.000000    13.5  ...    13.000000    12.5
             25%      12.000000    13.5  ...    13.625000    12.5
             50%      13.000000    13.5  ...    14.950000    12.5
             75%      13.500000    13.5  ...    15.350000    12.5
             max      16.000000    13.5  ...    22.200000    12.5
origin       count    13.000000     1.0  ...    10.000000     1.0
             mean      1.000000     3.0  ...     1.000000     3.0
             std       0.000000     NaN  ...     0.000000     NaN
             min       1.000000     3.0  ...     1.000000     3.0
             25%       1.000000     3.0  ...     1.000000     3.0
             50%       1.000000     3.0  ...     1.000000     3.0
             75%       1.000000     3.0  ...     1.000000     3.0
             max       1.000000     3.0  ...     1.000000     3.0

model_year                                                     81  \
cylinders                     4       5            6            4
mpg          count    25.000000     1.0     2.000000    21.000000
             mean     34.612000    36.4    25.900000    32.814286
             std       6.597621     NaN     9.616652     3.844904
             min      23.600000    36.4    19.100000    25.800000
             25%      29.800000    36.4    22.500000    30.000000
             50%      33.800000    36.4    25.900000    33.000000
             75%      40.800000    36.4    29.300000    34.700000
             max      46.600000    36.4    32.700000    39.100000
displacement count    25.000000     1.0     2.000000    21.000000
             mean    111.000000   121.0   196.500000   108.857143
             std      24.608603     NaN    40.305087    23.007142
             min      85.000000   121.0   168.000000    79.000000
             25%      90.000000   121.0   182.250000    91.000000
             50%      98.000000   121.0   196.500000   105.000000
             75%     134.000000   121.0   210.750000   120.000000
             max     156.000000   121.0   225.000000   156.000000
weight       count    25.000000     1.0     2.000000    21.000000
             mean   2360.080000  2950.0  3145.500000  2275.476190
             std     392.902333     NaN   333.047294   354.629753
             min    1835.000000  2950.0  2910.000000  1755.000000
             25%    2110.000000  2950.0  3027.750000  2045.000000
             50%    2265.000000  2950.0  3145.500000  2215.000000
             75%    2678.000000  2950.0  3263.250000  2490.000000
             max    3250.000000  2950.0  3381.000000  3230.000000
acceleration count    25.000000     1.0     2.000000    21.000000
             mean     17.144000    19.9    15.050000    16.466667
             std       2.585388     NaN     5.161880     2.015275
             min      13.800000    19.9    11.400000    12.900000
             25%      15.200000    19.9    13.225000    14.900000
             50%      16.500000    19.9    15.050000    16.200000
             75%      18.100000    19.9    16.875000    17.300000
             max      23.700000    19.9    18.700000    20.700000
origin       count    25.000000     1.0     2.000000    21.000000
             mean      2.200000     2.0     2.000000     2.095238
             std       0.816497     NaN     1.414214     0.943650
             min       1.000000     2.0     1.000000     1.000000
             25%       2.000000     2.0     1.500000     1.000000
             50%       2.000000     2.0     2.000000     2.000000
             75%       3.000000     2.0     2.500000     3.000000
             max       3.000000     2.0     3.000000     3.000000

model_year                                        82
cylinders                     6       8            4            6
mpg          count     7.000000     1.0    28.000000     3.000000
             mean     23.428571    26.6    32.071429    28.333333
             std       4.139531     NaN     5.054727     8.504901
             min      17.600000    26.6    23.000000    22.000000
             25%      21.300000    26.6    27.750000    23.500000
             50%      23.500000    26.6    32.000000    25.000000
             75%      24.800000    26.6    36.000000    31.500000
             max      30.700000    26.6    44.000000    38.000000
displacement count     7.000000     1.0    28.000000     3.000000
             mean    184.000000   350.0   118.571429   225.000000
             std      35.327043     NaN    21.439715    40.951190
             min     145.000000   350.0    91.000000   181.000000
             25%     157.000000   350.0   103.250000   206.500000
             50%     173.000000   350.0   112.000000   232.000000
             75%     212.500000   350.0   136.250000   247.000000
             max     231.000000   350.0   156.000000   262.000000
weight       count     7.000000     1.0    28.000000     3.000000
             mean   3093.571429  3725.0  2402.321429  2931.666667
             std     272.911987     NaN   332.756396    90.737717
             min    2725.000000  3725.0  1965.000000  2835.000000
             25%    2915.000000  3725.0  2125.000000  2890.000000
             50%    3060.000000  3725.0  2382.500000  2945.000000
             75%    3287.500000  3725.0  2646.250000  2980.000000
             max    3465.000000  3725.0  3035.000000  3015.000000
acceleration count     7.000000     1.0    28.000000     3.000000
             mean     15.442857    19.0    16.703571    16.033333
             std       2.593490     NaN     2.590364     1.193035
             min      12.600000    19.0    11.600000    14.700000
             25%      13.200000    19.0    14.925000    15.550000
             50%      15.800000    19.0    16.300000    16.400000
             75%      16.850000    19.0    18.050000    16.700000
             max      19.600000    19.0    24.600000    17.000000
origin       count     7.000000     1.0    28.000000     3.000000
             mean      1.714286     1.0     1.714286     1.000000
             std       0.951190     NaN     0.937180     0.000000
             min       1.000000     1.0     1.000000     1.000000
             25%       1.000000     1.0     1.000000     1.000000
             50%       1.000000     1.0     1.000000     1.000000
             75%       2.500000     1.0     3.000000     1.000000
             max       3.000000     1.0     3.000000     1.000000

[40 rows x 43 columns]

In [15]:
# assign into year_cyl => cutdown the code
year_cyl = df.groupby(['model_year', 'cylinders']).mean()

In [16]:
year_cyl

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [17]:
year_cyl.index.names

FrozenList(['model_year', 'cylinders'])

In [18]:
# grab the 2 outer levels
# return 2 list : the list of model year and the list of cylinder
year_cyl.index.levels

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [19]:
# grab the index
# loc command are going to reference the outer level
# in this case the outer level is the model year
# return the result based on the model year index
year_cyl.loc[70]

                 mpg  displacement       weight  acceleration    origin
cylinders
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [20]:
# passing the list
year_cyl.loc[[70, 82]]

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
82         4          1.714286
           6          1.000000

In [21]:
# grab 4 cylinders for the year 70 - based off exact row
# using the tuple in the year_cyl.index.levels
year_cyl.loc[(70,4)]

mpg               25.285714
displacement     107.000000
weight          2292.571429
acceleration      16.000000
origin             2.285714
Name: (70, 4), dtype: float64

# Cross Section
* Grab something have Multiple Index
* Method Call <b>".xs"</b>

In [23]:
# level is chosen column index
# key is the row you looking at
# key is the single value - not including two or more value
year_cyl.xs(key=70, level='model_year')

                 mpg  displacement       weight  acceleration    origin
cylinders
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [24]:
# work with multiple key
year_cyl.loc[[70,80]]

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000

In [26]:
# access to multiple 4 cylinder
# using the cross-section
# the actual level is not show in the results - because it only has one attribute or value for that level
four_cyl = year_cyl.xs(key=4, level='cylinders')

In [27]:
four_cyl

                  mpg  displacement       weight  acceleration    origin
model_year
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [34]:
# if you want to access to both 6 and 8 cylinders, you use the filter it first
df[df['cylinders'].isin([6,8])].groupby('cylinders').mean()

,mpg,displacement,weight,acceleration,model_year,origin
cylinders,,,,,,
6,19.985714,218.142857,3198.226190,16.263095,75.928571,1.190476
8,14.963107,345.009709,4114.718447,12.955340,73.902913,1.000000

In [36]:
df[df['cylinders'].isin([6,8])].groupby(['model_year', 'cylinders']).mean()

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         8          13.615385    344.846154  4228.384615     13.000000
73         6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         6          25.900000    196.500000  3145.500000     15.050000
81         6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         6          1.000000
           8          1.000000
71         6          1.000000
           8          1.000000
72         8          1.000000
73         6          1.250000
           8          1.000000
74         6          1.000000
           8          1.000000
75         6          1.000000
           8          1.000000
76         6          1.300000
           8          1.000000
77         6          1.400000
           8          1.000000
78         6          1.166667
           8          1.000000
79         6          1.000000
           8          1.000000
80         6          2.000000
81         6          1.714286
           8          1.000000
82         6          1.000000

In [37]:
# Swap index or level position
year_cyl.swaplevel()

,,mpg,displacement,weight,acceleration,origin
cylinders,model_year,,,,,
4,70,25.285714,107.000000,2292.571429,16.000000,2.285714
6,70,20.500000,199.000000,2710.500000,15.500000,1.000000
8,70,14.111111,367.555556,3940.055556,11.194444,1.000000
4,71,27.461538,101.846154,2056.384615,16.961538,1.923077
6,71,18.000000,243.375000,3171.875000,14.750000,1.000000
8,71,13.428571,371.714286,4537.714286,12.214286,1.000000
3,72,19.000000,70.000000,2330.000000,13.500000,3.000000
4,72,23.428571,111.535714,2382.642857,17.214286,1.928571
8,72,13.615385,344.846154,4228.384615,13.000000,1.000000
3,73,18.000000,70.000000,2124.000000,13.500000,3.000000
4,73,22.727273,109.272727,2338.090909,17.136364,2.000000
6,73,19.000000,212.250000,2917.125000,15.687500,1.250000
8,73,13.200000,365.250000,4279.050000,12.250000,1.000000
4,74,27.800000,96.533333,2151.466667,16.400000,2.200000
6,74,17.857143,230.428571,3320.000000,16.857143,1.000000
8,74,14.200000,315.200000,4438.400000,14.700000,1.000000
4,75,25.250000,114.833333,2489.250000,15.833333,2.166667
6,75,17.583333,233.750000,3398.333333,17.708333,1.000000
8,75,15.666667,330.500000,4108.833333,13.166667,1.000000
4,76,26.766667,106.333333,2306.600000,16.866667,1.866667
6,76,20.000000,221.400000,3349.600000,17.000000,1.300000
8,76,14.666667,324.000000,4064.666667,13.222222,1.000000
3,77,21.500000,80.000000,2720.000000,13.500000,3.000000
4,77,29.107143,106.500000,2205.071429,16.064286,1.857143
6,77,19.500000,220.400000,3383.000000,16.900000,1.400000
8,77,16.000000,335.750000,4177.500000,13.662500,1.000000
4,78,29.576471,112.117647,2296.764706,16.282353,2.117647
5,78,20.300000,131.000000,2830.000000,15.900000,2.000000
6,78,19.066667,213.250000,3314.166667,16.391667,1.166667
8,78,19.050000,300.833333,3563.333333,13.266667,1.000000
4,79,31.525000,113.583333,2357.583333,15.991667,1.583333
5,79,25.400000,183.000000,3530.000000,20.100000,2.000000
6,79,22.950000,205.666667,3025.833333,15.433333,1.000000
8,79,18.630000,321.400000,3862.900000,15.400000,1.000000
3,80,23.700000,70.000000,2420.000000,12.500000,3.000000
4,80,34.612000,111.000000,2360.080000,17.144000,2.200000
5,80,36.400000,121.000000,2950.000000,19.900000,2.000000
6,80,25.900000,196.500000,3145.500000,15.050000,2.000000
4,81,32.814286,108.857143,2275.476190,16.466667,2.095238
6,81,23.428571,184.000000,3093.571429,15.442857,1.714286
8,81,26.600000,350.000000,3725.000000,19.000000,1.000000
4,82,32.071429,118.571429,2402.321429,16.703571,1.714286
6,82,28.333333,225.000000,2931.666667,16.033333,1.000000

In [41]:
# sort the index
# it will make some sense to sort the outer level
# ascending = False => from high to low
year_cyl.sort_index(level='model_year', ascending=False)

                            mpg  displacement       weight  acceleration  \
model_year cylinders
82         6          28.333333    225.000000  2931.666667     16.033333
           4          32.071429    118.571429  2402.321429     16.703571
81         8          26.600000    350.000000  3725.000000     19.000000
           6          23.428571    184.000000  3093.571429     15.442857
           4          32.814286    108.857143  2275.476190     16.466667
80         6          25.900000    196.500000  3145.500000     15.050000
           5          36.400000    121.000000  2950.000000     19.900000
           4          34.612000    111.000000  2360.080000     17.144000
           3          23.700000     70.000000  2420.000000     12.500000
79         8          18.630000    321.400000  3862.900000     15.400000
           6          22.950000    205.666667  3025.833333     15.433333
           5          25.400000    183.000000  3530.000000     20.100000
           4          31.525000    113.583333  2357.583333     15.991667
78         8          19.050000    300.833333  3563.333333     13.266667
           6          19.066667    213.250000  3314.166667     16.391667
           5          20.300000    131.000000  2830.000000     15.900000
           4          29.576471    112.117647  2296.764706     16.282353
77         8          16.000000    335.750000  4177.500000     13.662500
           6          19.500000    220.400000  3383.000000     16.900000
           4          29.107143    106.500000  2205.071429     16.064286
           3          21.500000     80.000000  2720.000000     13.500000
76         8          14.666667    324.000000  4064.666667     13.222222
           6          20.000000    221.400000  3349.600000     17.000000
           4          26.766667    106.333333  2306.600000     16.866667
75         8          15.666667    330.500000  4108.833333     13.166667
           6          17.583333    233.750000  3398.333333     17.708333
           4          25.250000    114.833333  2489.250000     15.833333
74         8          14.200000    315.200000  4438.400000     14.700000
           6          17.857143    230.428571  3320.000000     16.857143
           4          27.800000     96.533333  2151.466667     16.400000
73         8          13.200000    365.250000  4279.050000     12.250000
           6          19.000000    212.250000  2917.125000     15.687500
           4          22.727273    109.272727  2338.090909     17.136364
           3          18.000000     70.000000  2124.000000     13.500000
72         8          13.615385    344.846154  4228.384615     13.000000
           4          23.428571    111.535714  2382.642857     17.214286
           3          19.000000     70.000000  2330.000000     13.500000
71         8          13.428571    371.714286  4537.714286     12.214286
           6          18.000000    243.375000  3171.875000     14.750000
           4          27.461538    101.846154  2056.384615     16.961538
70         8          14.111111    367.555556  3940.055556     11.194444
           6          20.500000    199.000000  2710.500000     15.500000
           4          25.285714    107.000000  2292.571429     16.000000

                        origin
model_year cylinders
82         6          1.000000
           4          1.714286
81         8          1.000000
           6          1.714286
           4          2.095238
80         6          2.000000
           5          2.000000
           4          2.200000
           3          3.000000
79         8          1.000000
           6          1.000000
           5          2.000000
           4          1.583333
78         8          1.000000
           6          1.166667
           5          2.000000
           4          2.117647
77         8          1.000000
           6          1.400000
           4          1.857143
           3          3.000000
76         8          1.000000
           6          1.300000
           4          1.866667
75         8          1.000000
           6          1.000000
           4          2.166667
74         8          1.000000
           6          1.000000
           4          2.200000
73         8          1.000000
           6          1.250000
           4          2.000000
           3          3.000000
72         8          1.000000
           4          1.928571
           3          3.000000
71         8          1.000000
           6          1.000000
           4          1.923077
70         8          1.000000
           6          1.000000
           4          2.285714

In [43]:
# return the agg function list
df.agg(['std', 'mean'])['mpg']

std      7.815984
mean    23.514573
Name: mpg, dtype: float64

In [44]:
# using the list to perform the aggregate functions
# the key is the column you want to perform the aggregate functions
# the value is the aggregate function
df.agg({'mpg':['std', 'mean'], 'cylinders':['max', 'mean']})

            mpg  cylinders
std    7.815984        NaN
mean  23.514573   5.454774
max         NaN   8.000000